### ISSUE TITLE
Remove C++ NativeAOT workaround once it's not needed anymore

### ISSUE THREAD

**Issue by lemonmojo** [royalapplications/beyondnet#60]
Issue was introduced in .NET 8 RC1.

See https://github.com/dotnet/runtime/issues/91997

**Comment by lemonmojo** [comment]
See https://github.com/dotnet/runtime/pull/92114

**Comment by nil4** [comment]
A couple more reasons to look forward to RC2:
- https://github.com/dotnet/runtime/issues/92297
- https://github.com/dotnet/runtime/issues/92491

**Comment by lemonmojo** [comment]
As this was fixed in RC2, the workarounds have been removed in https://github.com/royalapplications/beyondnet/commit/e1336106d4a7ba6df72473f79cfc9d5347bc1cdb.
