### ISSUE TITLE
Consider excluding interfaces containing static members

### ISSUE THREAD

**Issue by nil4** [royalapplications/beyondnet#76]
Consider updating the generator to exclude interfaces containing any `static` members (methods or properties.) 

Such interfaces cannot be used directly, but only as type parameters to generic methods; the code generated does not compile successfully.

Consider this example:

```csharp
interface ISample {
    void RegularMethod();
    static abstract void StaticMethod();
    static abstract int StaticProperty { get; }
}

class Sample : ISample {
    public void RegularMethod() {}
    public static void StaticMethod() {}
    public static int StaticProperty => 42;
}
```

The generated code would look like this:

```csharp
[UnmanagedCallersOnly(EntryPoint = "SampleNamespace_ISample_StaticMethod")]
internal static void /* System.Void */ SampleNamespace_ISample_StaticMethod(void** /* System.Exception */ __outException) {
    try {
        SampleNamespace.ISample.StaticMethod();
        /* elided */
    } catch (Exception __exception) { /* elided */ } finally {}
}

[UnmanagedCallersOnly(EntryPoint = "SampleNamespace_ISample__StaticProperty_Get")]
internal static void* /* int */ SampleNamespace_ISample_StaticProperty_Get(void* /* SampleNamespace.ISample */ __self, void** /* System.Exception */ __outException)
{
    SampleNamespace.ISample __selfConverted = InteropUtils.GetInstance<SampleNamespace.ISample>(__self);
}
```

The compiler then fails:

> Generated_CS.cs(4,9): Error CS8926 : A static virtual or abstract interface member can be accessed only on a type parameter.
> 
> Generated_CS.cs(12,47): Error CS8920 : The interface 'ISample' cannot be used as type argument. Static member 'ISample.StaticProperty.get' does not have a most specific implementation in the interface.

Since the Swift projection does not support generics, the interface `ISample` is not currently usable. However, the class `Sample` can still be projected correctly and all of its APIs *are* directly usable.

It seems therefore worthwhile to filter out interfaces containing any `static` members from the projection.

**Comment by lemonmojo** [comment]
Fixed in https://github.com/royalapplications/beyondnet/pull/77. thx @nil4!
