### ISSUE TITLE
.NET 9.0 To-Do's

### ISSUE THREAD

**Issue by nil4** [royalapplications/beyondnet#85]
.NET 9.0 RC1 release does not include any XML documentation files (possible related to https://github.com/dotnet/runtime/issues/106825 or https://github.com/dotnet/runtime/issues/105974#issuecomment-2278395449)

When RC2 is released in Oct, and then RTM in Nov, check if XML files are present, and if so, remove the temporary workaround:

https://github.com/royalapplications/beyondnet/blob/c6a9fe42dd51c8926b16751ee2663eeb7575c7c5/Generator/Beyond.NET.CodeGenerator.CLI/Source/CodeGeneratorDriver.cs#L217-L218

**Comment by lemonmojo** [comment]
Just for reference, here's the generated files with RC1: https://github.com/royalapplications/beyondnet/commit/0746d4b86b3042290cb7f0e56a82bd67eeaa46fc
