### ISSUE TITLE
Add description for new ExcludedAssemblyNames setting to readme

### ISSUE THREAD

**Issue by lemonmojo** [royalapplications/beyondnet#94]
@nil4 No hurry and thx for the [Christmas present](https://github.com/royalapplications/beyondnet/pull/93) 😉 🎁 🎄

**Comment by nil4** [comment]
Done in https://github.com/royalapplications/beyondnet/commit/af2e3868d7867b8408d216207ed006d66e4dbe52 🎅 🚀
